modLoader="javafml"
loaderVersion="[28,)"
[[mods]] 
modId="easyflint" 
version="1.0" 
displayName="Easy Flint" 
authors="lerrific" 
description='''
A simple mod that allows you to right click with an empty hand on a gravel block a few times to get flint.
'''